### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by ClaudiFaucan** [Freddrickk/INF7741#3]
Hello,

I have an issue on make command :

`$ make
mkdir -p bin/
nitc --debug src/tool.nit -o bin/tool
mkdir -p bin/
nitc --debug src/interpreter.nit -o bin/interpreter
mkdir -p bin/
nitc --debug src/debugger.nit -o bin/debugger
src/readline_.nit:4:32: fatal error: readline/readline.h: No such file or directory
compilation terminated.
make[1]: *** [readline_95d._ffi.extern.o] Error 1
Compilation Error: `make` failed with error code: 512. The command was `make -B -C nit_compile -f debugger.mk -j 4 `.
Errors: 1. Warnings: 0.
Makefile:18: recipe for target 'bin/debugger' failed
make: *** [bin/debugger] Error 1
`

**Comment by ppepos** [comment]
You need Gnu Readline headers. Typically `libreadline-dev` package holds it (for debian based distros).
